### PR TITLE
Switch to GitHub Actions

### PR DESCRIPTION
**Pull request by nschonni**
Related to #30

- It currently isn't restricted to the master branch, but that can be added
- The beta/modules setup doesn't seem to work, but I don't think it was before either
- I believe the RuboCop fixes that were flagged are for Ruby 2.3+, so I'm not sure if there are other implications

Example run with this can be seen here https://github.com/nschonni/homebrew-sass/actions/runs/31635091

### CODE REVIEW

**Comment by nex3** [comment]
Thanks for taking initiative on this, Nick!

I think we can probably manage to make this work while sticking to Travis. Would you be interested in working on that?

**Comment by nschonni** [comment]
I can take a look, but I've found GitHub Actions alot faster for OSX stuff. I get the change of CI isn't a usual thing, but was there a reason to stick with Travis for this repo?

**Comment by nex3** [comment]
It's consistent with the rest of the Sass infrastructure, and it's not tightly coupled to GitHub.

**Comment by nschonni** [comment]
OK, i'm not sure when I'll get back to it. BTW, Travis is tightly coupled to GitHub, since it's the only source control provider they support. I'm not ripping out Travis in all my projects, just the Mac backlog has always been slow there

**Pull request merged**
